version: '3.9'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pm101
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    restart: "no"
volumes:
    db_data: {}